version: '2'
services:
  # from https://hub.docker.com/r/mkroli/karaf/
  karaf:
      image: mkroli/karaf:4.0 # 4.1 docker image broken
      container_name: karaf
      ports:
        - "11099:1099"
        - "144444:44444"
        - "18101:8101"
        - "18181:8181" # web consol
      volumes:
        - ./karaf-deploy:/deploy
        - ./karaf-log:/opt/karaf/data/log
        - ./org.ops4j.pax.logging.cfg:/opt/karaf/etc/org.ops4j.pax.logging.cfg

      #  - ./karaf-etc:/opt/karaf/etc
      #  - ./karaf-data:/opt/karaf/data
      # restart: always
      env_file:
        - .karaf.env
      networks:
        - opennms-plugin-shop-network
      entrypoint: /opt/karaf/bin/karaf

networks:
  opennms-plugin-shop-network:
      driver: bridge