

version: '2'
services:
  # from https://hub.docker.com/r/mkroli/karaf/
  karaf:
      image: mkroli/karaf:4.0 # 4.1 docker image broken
      container_name: karaf
      ports:
        - "11099:1099"
        - "144444:44444"
        - "18101:8101"
        - "18181:8181" # web consol
      volumes:
        - ./karaf-deploy:/deploy
        - ./karaf-etc:/opt/karaf/etc
        - ./karaf-data:/opt/karaf/data
      # restart: always
      networks:
        - opennms-plugin-shop-network
      entrypoint: /opt/karaf/bin/karaf

# from https://github.com/nezhar/wordpress-docker-compose/blob/master/docker-compose.yml
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 127.0.0.1:80:80 # change ip if required
    volumes:
      - ./wp-app:/var/www/html # Full wordpress project
      # link to easy digtal downloads git clone checked out from
      # Easy Digital Downloads from https://github.com/easydigitaldownloads/easy-digital-downloads
      # Use release/2.4 branch
      - /home/admin/devel/gitrepos/Easy-Digital-Downloads/:/var/www/html/wp-content/plugins/easy-digital-downloads 
      # Local osgi manager extension to EDD 
      - ../edd-downloads-as-osgi:/var/www/html/wp-content/plugins/edd-downloads-as-osgi # Plugin development
     
      # any other plugins
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - opennms-plugin-shop-network
  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - 127.0.0.1:3306:3306 # change ip if required
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password
    networks:
      - opennms-plugin-shop-network
networks:
  opennms-plugin-shop-network:
      driver: bridge