/*
 * Copyright 2014 OpenNMS Group Inc., Entimoss ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.opennms.features.pluginmgr.vaadin.pluginmanager;

import org.opennms.karaf.licencemgr.metadata.jaxb.ProductMetadata;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.shared.ui.label.ContentMode;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;

public class ProductDescriptorPanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,5","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Label licenceAuthenticatedLabel;
	@AutoGenerated
	private CheckBox licenceRequiredCheckBox;
	@AutoGenerated
	private TextField organizationTextField;
	@AutoGenerated
	private TextField licenceTypeTextField;
	@AutoGenerated
	private TextField featureRepositoryTextField;
	@AutoGenerated
	private TextField productUrlTextField;
	@AutoGenerated
	private TextArea productDescriptionTextArea;
	@AutoGenerated
	private TextField productIdTextField;
	@AutoGenerated
	private TextField productNameTextField;
	private static final long serialVersionUID = 1L;
	
	private boolean noUpdate=true; // sets field to read only
	
	public boolean getNoUpdate() {
		return noUpdate;
	}

	public void setNoUpdate(boolean noUpdate) {
		this.noUpdate = noUpdate;
	}

	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */

	public ProductDescriptorPanel() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
		licenceAuthenticatedLabel.setContentMode(ContentMode.HTML);
		licenceAuthenticatedLabel.setValue("");

	}
	
	public synchronized void setProductMetadata(ProductMetadata productMetadata){
		productIdTextField.setReadOnly(false);
		productIdTextField.setValue( (productMetadata.getProductId()==null )?  "":productMetadata.getProductId());
		productIdTextField.setReadOnly(noUpdate);
		
		productNameTextField.setReadOnly(false);
		productNameTextField.setValue( (productMetadata.getProductName()==null )?  "":productMetadata.getProductName());
		productNameTextField.setReadOnly(noUpdate);
		
		featureRepositoryTextField.setReadOnly(false);
		featureRepositoryTextField.setValue(( productMetadata.getFeatureRepository()== null ) ? "": productMetadata.getFeatureRepository());
		featureRepositoryTextField.setReadOnly(noUpdate);
	
		licenceTypeTextField.setReadOnly(false);
		licenceTypeTextField.setValue( (productMetadata.getLicenceType()==null )?  "":productMetadata.getLicenceType());
		licenceTypeTextField.setReadOnly(noUpdate);
		
		organizationTextField.setReadOnly(false);
		organizationTextField.setValue( (productMetadata.getOrganization()==null ) ? "":productMetadata.getOrganization());
		organizationTextField.setReadOnly(noUpdate);
		
		productDescriptionTextArea.setReadOnly(false);
		productDescriptionTextArea.setValue( (productMetadata.getProductDescription()==null ) ? "":productMetadata.getProductDescription());
		productDescriptionTextArea.setReadOnly(noUpdate);
		
		productUrlTextField.setReadOnly(false);
		productUrlTextField.setValue( (productMetadata.getProductUrl()==null ) ? "":productMetadata.getProductUrl());
		productUrlTextField.setReadOnly(noUpdate);

		licenceRequiredCheckBox.setReadOnly(false);
		licenceRequiredCheckBox.setValue( (productMetadata.getLicenceKeyRequired()==null ) ? false :productMetadata.getLicenceKeyRequired());
		licenceRequiredCheckBox.setReadOnly(noUpdate);
		
		licenceAuthenticatedLabel.setVisible(false);
		if (productMetadata.getLicenceKeyRequired()!=null && productMetadata.getLicenceKeyRequired()==true){
			// only generate label if licenceKeyAuthenticated is not null
			if (productMetadata.getLicenceKeyAuthenticated()!=null){
				if ( productMetadata.getLicenceKeyAuthenticated()==true ){
					licenceAuthenticatedLabel.setValue("<div style=\"color: green;\">licence is authenticated</div>");
				} else {
					licenceAuthenticatedLabel.setValue("<div style=\"color: red;\">licence is not authenticated</div>");
				}
				licenceAuthenticatedLabel.setVisible(true);
			}

		}
		
	}
	
	public synchronized ProductMetadata getProductMetadata(){

		ProductMetadata productMetadata= new ProductMetadata();

		productMetadata.setProductId(productIdTextField.getValue());

		productMetadata.setProductName(productNameTextField.getValue());

		productMetadata.setFeatureRepository(featureRepositoryTextField.getValue());

		productMetadata.setLicenceType(licenceTypeTextField.getValue());

		productMetadata.setOrganization(organizationTextField.getValue());

		productMetadata.setProductDescription(productDescriptionTextArea.getValue());

		productMetadata.setProductUrl(productUrlTextField.getValue());

		productMetadata.setLicenceKeyRequired(licenceRequiredCheckBox.getValue());
		
		return productMetadata;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(true);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);
		mainLayout.setSpacing(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// productNameTextField
		productNameTextField = new TextField();
		productNameTextField.setCaption("Product Name");
		productNameTextField.setImmediate(true);
		productNameTextField.setWidth("100.0%");
		productNameTextField.setHeight("-1px");
		mainLayout.addComponent(productNameTextField);
		
		// productIdTextField
		productIdTextField = new TextField();
		productIdTextField.setCaption("Product Id");
		productIdTextField.setImmediate(true);
		productIdTextField.setWidth("100.0%");
		productIdTextField.setHeight("-1px");
		mainLayout.addComponent(productIdTextField);
		
		// productDescriptionTextArea
		productDescriptionTextArea = new TextArea();
		productDescriptionTextArea.setCaption("Product Description");
		productDescriptionTextArea.setImmediate(true);
		productDescriptionTextArea.setWidth("100.0%");
		productDescriptionTextArea.setHeight("6.0em");
		mainLayout.addComponent(productDescriptionTextArea);
		
		// productUrlTextField
		productUrlTextField = new TextField();
		productUrlTextField.setCaption("Product URL");
		productUrlTextField.setImmediate(true);
		productUrlTextField.setWidth("100.0%");
		productUrlTextField.setHeight("-1px");
		mainLayout.addComponent(productUrlTextField);
		
		// featureRepositoryTextField
		featureRepositoryTextField = new TextField();
		featureRepositoryTextField.setCaption("Feature Repository URL");
		featureRepositoryTextField.setImmediate(true);
		featureRepositoryTextField.setWidth("100.0%");
		featureRepositoryTextField.setHeight("-1px");
		mainLayout.addComponent(featureRepositoryTextField);
		
		// licenceTypeTextField
		licenceTypeTextField = new TextField();
		licenceTypeTextField.setCaption("Licence Type");
		licenceTypeTextField.setImmediate(true);
		licenceTypeTextField.setWidth("100.0%");
		licenceTypeTextField.setHeight("-1px");
		licenceTypeTextField.setNullSettingAllowed(true);
		mainLayout.addComponent(licenceTypeTextField);
		
		// organizationTextField
		organizationTextField = new TextField();
		organizationTextField.setCaption("Organization");
		organizationTextField.setImmediate(true);
		organizationTextField.setWidth("100.0%");
		organizationTextField.setHeight("-1px");
		organizationTextField.setNullSettingAllowed(true);
		mainLayout.addComponent(organizationTextField);
		
		// licenceRequiredCheckBox
		licenceRequiredCheckBox = new CheckBox();
		licenceRequiredCheckBox.setCaption("Licence Key Required");
		licenceRequiredCheckBox.setImmediate(true);
		licenceRequiredCheckBox.setWidth("-1px");
		licenceRequiredCheckBox.setHeight("-1px");
		mainLayout.addComponent(licenceRequiredCheckBox);
		
		// licenceAuthenticatedLabel
		licenceAuthenticatedLabel = new Label();
		licenceAuthenticatedLabel.setImmediate(true);
		licenceAuthenticatedLabel
				.setDescription("State of licence authentication  for the systemId of this karaf instance");
		licenceAuthenticatedLabel.setWidth("-1px");
		licenceAuthenticatedLabel.setHeight("-1px");
		licenceAuthenticatedLabel.setValue("Label");
		mainLayout.addComponent(licenceAuthenticatedLabel);
		
		return mainLayout;
	}


}
